# pr001.yml
---

rhbase_firewall_allow_services:
  - dhcp

dhcp_global_domain_name_servers:
  - 172.16.255.254

dhcp_global_default_lease_time: 43200
dhcp_global_max_lease_time: 43200 # 12 hrs
dhcp_global_domain_name: avalon.lan

dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    routers: 172.16.255.254
    pools:
      - range_begin: 172.16.128.1
        range_end: 172.16.191.254
        deny: 'members of "vbox"'
      - range_begin: 172.16.192.1
        range_end: 172.16.255.253
        allow: 'members of "vbox"'

dhcp_hosts:
  - name: werkstation
    mac: '08:00:27:1E:41:47'  # eerste adapter van Fedora 25
    ip: 172.16.128.10
